*

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!turbo.json

!apps/
!apps/merchant/
!apps/merchant/**

!packages/
!packages/**

**/node_modules
**/.next
**/.turbo
**/tsconfig.tsbuildinfo
**/*.log
.env
.env.*
!**/.env.example
